import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center gap-4">
          <Button asChild>
            <Link
              href="https://github.com/sahidrahman404/frontend"
              target="_blank"
            >
              Frontend Source Code
            </Link>
          </Button>
          <Button asChild>
            <Link
              href="https://github.com/sahidrahman404/backend"
              target="_blank"
            >
              Backend Source Code
            </Link>
          </Button>
        </div>
        {children}
      </body>
    </html>
  );
}
